version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 0.0.0.0:80:80
    environment:
      WORDPRESS_DB_HOST: wp_db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: pass1234
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html

  wp_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: pass1234
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wp_db:/var/lib/mysql

volumes:
  wordpress:
  wp_db:
